### PR TITLE
add with-keys macro

### PR DESCRIPTION
**Pull request by prasant94**
This is the latest code with the macro, I'll add the tests later but I thought atleast we should have this instead of the old code.

### CODE REVIEW

**Comment by prasant94** [comment]
Hey, I am sorry, I haven't handled the nil case. I'll just do that and push again. Sorry about all the confusion

**Comment by mikera** [comment]
Thats OK. It's fine to add extra commits and push by the way: the PR will be automatically updated since the PR is tied to the branch, not the specific commits

**Comment by mikera** [comment]
Also best practice is usually to make a new branch for PRs (rather than than using develop for everything). This can help a lot if you are developing a couple of different long-lived branches in parallel. It doesn't really matter for short lived changes of course.

**Comment by prasant94** [comment]
I also added PCholeskyDecomposition. The vectorz implementation currently uses SimpleCholesky which doesnt return null in case of failure. But I still added an if statement to return null for when the implementation is switched to the other one.

Travis CI is failing. I think this needs a new release.

**Comment by mikera** [comment]
What do you need a new release of? Vectorz?

Does Vectorz need some changes to handle the null result case?

**Comment by prasant94** [comment]
I need the a release for core.matrix that has the new protocols Aleksandr added.

For Cholesky decomposition, there are three implementations available. SimpleCholesky, Cholesky and CholeskyInner.
Right now, SimpleCholesky is used.

``` java
public class Cholesky {
    public static final ICholeskyResult decompose(AMatrix a) {
        return SimpleCholesky.decompose(a.toMatrix());
    }
    public static final ICholeskyResult decompose(Matrix a) {
        return SimpleCholesky.decompose(a);
    }
}
```

Cholesky and CholeskyInner return null for invalid matrices. SimpleCholesky returns some incorrect answer.

**Comment by mikera** [comment]
OK I made a new core.matrix release. Let me know if it does the job!

**Comment by prasant94** [comment]
Yes, this works. Thanks!

**Comment by mikera** [comment]
Great stuff! merging this in now.

**Pull request merged**
