### PR TITLE
combiner vector-norm and matrix-norm into a single norm method.

### PR DESCRIPTION
**Pull request by prasant94**

### CODE REVIEW

**Comment by prasant94** [comment]
```
FAIL in (compliance-test) (compliance_tester.clj:763)
expected: (= (row-count R) 2)
  actual: (not (= 4 2))
```

This is one of the older tests. I barely added anything, that shouldn't have affected it.

**Comment by mikera** [comment]
Can you investigate? Might be an invalid assumption. Or I might have broken something with my recent changes.... try running the code from the test at the REPL and see what you get.

**Comment by prasant94** [comment]
its the compact option for QR decomposition...vectorz-clj didn't support that until now. I'll add it.

**Comment by prasant94** [comment]
yup...good to go

**Comment by mikera** [comment]
Looks good, thanks!

**Pull request merged**
