### PR TITLE
Implementation for PSolveLinear and PLeastSquares

### PR DESCRIPTION
**Pull request by prasant94**

### CODE REVIEW

**Comment by mikera** [comment]
I think there should be at least an `avector-coerce` in the protocol implementations? You can't guarantee that the input will always be an `AVector` (might be a Clojure vector, for example).

Good to have a test or two that check this behaviour.

**Comment by mikera** [comment]
`(.asVector (matrix [[4 -1 2]]))` is better written as `(array [4 -1 2])`

**Comment by prasant94** [comment]
is this good?

**Comment by mikera** [comment]
Looks better! 

You should remove the `^AVector` type hints - these might cause a problem if the argument isn't actually an `AVector`.

Also can you add a test case that uses Clojure vectors, just to ensure that the `averctor-coerce` is working as intended? This stuff is a bit fiddly to get correct, so good to have extra tests.

**Comment by mikera** [comment]
@Prasant94 did you amend this yet? Would be good to get merged in before GSoC ends!

**Comment by prasant94** [comment]
We'll need a vectorz release for this. I am sending  a PR over there.

**Comment by prasant94** [comment]
This can be merged now

**Comment by mikera** [comment]
Looks good!

**Pull request merged**
