### PR TITLE
add SVD and LU decomposition protocols

### PR DESCRIPTION
**Pull request by prasant94**

### CODE REVIEW

**Comment by mikera** [comment]
Looks good!

**Comment by mikera** [comment]
You could use `with-keys` on the LUP decomposition as well.... nice to have

**Comment by prasant94** [comment]
The lu protocol method takes only one argument. It doesn't take any options.

**Comment by mikera** [comment]
Currently that is true.

But do you think it should it take some options?

**Comment by prasant94** [comment]
Yes, the user may not need the pivot matrix sometimes. We should have the user specify what matrices they wish to get just like in the other decompositions.

**Comment by mikera** [comment]
Can we clearly identify the use cases where a pivot matrix is not needed?

**Pull request merged**
