### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by mars0i**
First time I've done a pull request.  Let me know if there's something wrong.  Do you want me to squash away all of the different commits?  I understand that I can do that with git rebase.  (Is there a way to exclude pom.xml and project.clj?)

### CODE REVIEW

**Comment by mikera** [comment]
Code looks good, thanks!

We need to get a new version of core.matrix released first, so that this can depend on the new released core.matrix version with updated protocols / API functions. We want to avoid depending on SNAPSHOT versions, that makes it hard for people who don't have the latest snapshot of dependencies at hand.

Will also need to tidy up the pom / project.clj to reflect the new release and remove your local modifications.

After that we should be good to merge!

**Comment by mikera** [comment]
Looks good, I will merge this in now - thanks!

**Comment by mars0i** [comment]
Great.  (Will send CA tomorrow.)

**Comment by mikera** [comment]
Great, thanks!

(P.S. the CA isn't needed for vectorz-clj, only core.matrix itself.....)

**Pull request merged**
