### PR TITLE
add qr

### PR DESCRIPTION
**Pull request by prasant94**
Hey, do I revert the changes in pom.xml?

After I added this protocol, I did this in core.matrix:

``` clojure
=> (def m (matrix [[1 2 3][4 5 6][7 8 9]]))
=> (set-current-implementation :vectorz)
=> (def qrr (qr m))
=> (mmul (qrr :Q) (qrr :R))
[[0.9999999999999989 1.9999999999999978 2.9999999999999973] [3.9999999999999996 5.0 5.999999999999998] [7.0 7.999999999999999 8.999999999999998]]
=> (def qrr (qr m {:return [:R]}))
=> (def r (qrr :R))
=> (def qrr (qr m {:return [:Q]}))
=> (def q (qrr :Q))
=> (mmul q r)
[[0.9999999999999989 1.9999999999999978 2.9999999999999973] [3.9999999999999996 5.0 5.999999999999998] [7.0 7.999999999999999 8.999999999999998]]
```

and it gave the expected result, but I dont know how to tell if it actually used the vectorz.

### CODE REVIEW

**Comment by mikera** [comment]
Hi Prasant, it looks like you have done exactly the right thing.

However Travis CI build will fail on SNAPSHOT versions (since it can't find the right dependency in Maven Central...).

Let me release a new version of Vectorz today, then you should be able to make it work with `0.33.0`

**Comment by mikera** [comment]
OK @prasant94  I have released a new version of core.matrix (0.24.0) and Vector (0.33.0). You should be able to use these successfully and update the PR - any problems let me know!

**Comment by prasant94** [comment]
Done! :)

**Comment by mikera** [comment]
On the key handling, can you ensure that:

a) The `nil` option returns all keys? That should be the default.....
b) If a subset of keys is used, then getQ and getR only get called for the components requested. It completely defeats the purpose otherwise :-)

You may wish to consider a little helper macro for this...

**Comment by prasant94** [comment]
what if `(options :return)` is `nil`?

**Comment by mikera** [comment]
Same thing: if `(options :return)` is nil then we should use the default (all keys returned).

This is fairly conventional in Clojure land: default values get used unless specified otherwise.

**Comment by prasant94** [comment]
done finally

**Comment by mikera** [comment]
Hmmm can you think of some ways to make the conditional code around the keys much cleaner? That is some pretty ugly code.....

If you are clever then it should be possible to make the following work:

``` clojure
(qr [m options]
  (let [result (QR/decompose m)]
    (with-keys (:return options)
       {:Q (.getQ result) :R (.getR result)})))
```

 Where `with-keys` is a macro....

**Comment by prasant94** [comment]
Since all decompositions are going to need this, I will try to write a common macro that works for all of them.

**Comment by mikera** [comment]
Yes that makes sense. Happy to discuss some tricks on our call later if you need it!

**Comment by prasant94** [comment]
Hey, so this is what I came up with

``` clojure
(defmacro with-keys [hm ks]
  (select-keys hm ks))

(extend-protocol mp/PQRDecomposition
  AMatrix
    (qr [m options]
      (let
        [result (QR/decompose m)]
        (with-keys {:Q (.getQ result) :R (.getR result)} (:return options)))))
```

When I pass [:Q] directly to the macro seems to work fine, but if I pass (:return options), then it doesn't work

``` clojure
=> (macroexpand '(with-keys {:Q (.getQ result) :R (.getR result)} [:Q]))
{:Q (.getQ result)}
=> (def options {:return [:Q]})
=> (macroexpand '(with-keys {:Q (.getQ result) :R (.getR result)} (:return options)))
{}
```

How do I get (:return options) to turn into [:Q] as in goes into the macro?
I tried 

``` clojure
(defmacro with-keys [hm ks]
  (select-keys hm (eval ks)))
```

which works fine in the repl but throws a compiler exception in eclipse when I run shift+alt+s
`CompilerException java.lang.InstantiationException: mikera.vectorz.matrix_api$eval35155$fn__35156$eval35157__35158, compiling:(mikera/vectorz/matrix_api.clj:243:9)`

**Comment by mikera** [comment]
Well you have to think about the distinction between compile time (macro expansion time) and run time. `(:return options)` is a form at macro expansion time - so it isn't useful as a parameter to `select-keys`. `select-keys` needs to be executed at runtime, so it needs to be quoted.....

My recommendation is to write out the code that you want the macro to expand to first. That will help you write the macro correctly.

**Comment by prasant94** [comment]
But if the unwanted options have to be eliminated, that must be done at compile time, right? before the get methods are called. 
I was trying to use select-keys to remove the unwanted key value pairs before the value is evaluated. How can the macro know what keys have to be removed if it cant access the value of `(:return options)`?

This is the code I have written, that I want the marco to expand

``` clojure
(defn qr
  [m options]
  (let [result QR/decompose]
    (if (or (nil? options) (nil? (:return options)))
      {:Q (.getQ result) :R (.getR result)}
      (with-keys {:Q (.getQ result) :R (.getR result)} (:return options)))))
```

Am I approaching it the wrong way or is it even possible to do this with macros? What I have in mind is that I pass a hash of the symbols and the `getX result` calls along with a vector of required symbols and the macro removes the unwanted key-value pairs from the hash without evaluating them. The remaining calls get evaluated during runtime back in the actual function.

**Comment by mikera** [comment]
You can't eliminate the `getXXX` code blocks at compile time - it has to remain since the code has to be able to call these get methods at runtime (for certain values of options....). Your macro cannot possibly eliminate these.

However you _can_ use a macro to create code that doesn't _execute_ the `getXXX` functions unless they are needed.... can you think of a way to do that?

Hopefully that is enough clues - I want you to have the experience of solving this one for yourself!

**Comment by mikera** [comment]
P.S. I think the macro should be able to handle the `(if (or (nil? options) (nil? (:return options)))....` part as well.....

**Comment by mikera** [comment]
When I say "write out the code" I also mean write out the full code that you would expend the macro to expand to.... with all macros fully expanded

**Comment by prasant94** [comment]
Okay, I finally got it.
- `available` is `[:Q :R]`, ie all available choices.
- `options` is the options hashmap passed by the user (eg: `{:return [:Q :R :S]}`.
- `valid` is a seq of the required matrices after removing invalid and duplicate choices (eg: for the above \* example, `valid` is `(:Q :R)`.
- `matrices` is a seq of calls that correspond to each of the valid choices.

``` clojure
(defmacro with-keys [available options]
  `(letfn
    [(remove-invalid# [ls#] (filter (fn [x#] (not (nil? (some #{x#} ~available)))) (distinct ls#)))
     (generate-calls# [ls#] (map (fn [sym#] (eval (read-string (str "(.get" (name sym#) " result)")))) ls#))]
    (cond
      (or (nil? ~options) (nil? (:return ~options)))
        (let [matrices# (generate-calls# ~available)]
          (zipmap ~available matrices#))
      :else
        (let [valid# (remove-invalid# (:return ~options))
              matrices# (generate-calls# valid#)]
        (zipmap valid# matrices#)))))

(extend-protocol mp/PQRDecomposition
  AMatrix
    (qr [m options]
      (let
        [result (QR/decompose m)]
        (with-keys [:Q :R] options))))
```

You said that in this case, using read-string is safe. So I hope that is okay.

**Comment by mikera** [comment]
Getting better but I still think you can improve this! I'm keen you get the full experience regarding how to master macros.

Some more hints:
- Do it without `eval`. `eval` is almost always a code smell, and you don't need it here
- The macro should probably take `(:return options)`. There might be other things in the options map at some point, but they won't be relevant to `with-key`.
- Do it without constructing the `(.getXXX  ...)` calls. These should be passed into the macro as parameters. I suggest figuring out how to make `(with-keys {:Q (.getQ result) .....} (:return options))` work

**Comment by prasant94** [comment]
Ok, I think I'll get it right this time

**Comment by mikera** [comment]
You don't need the quotes to make this macro work. In fact, they will make it more complicated.

You might want to try a few simpler examples to master how macros work. Here's the most trivial example I can think of that highlights a key insight:

``` clojure
(defmacro text-form [op]
     (str op))

(text-form (.toString nil))
=> ??
```

Think about that a bit... did `(.toString nil)` ever get called? Why not?

**Comment by mikera** [comment]
Also try:

``` clojure
(text-form '(.toString nil))
=> ??
```

What do you learn? Which is easier to use in the context of macros?

**Comment by prasant94** [comment]
that arguments to macros behave like nested lists inside the macro body?

**Comment by mikera** [comment]
It's not just "behave like". They _are_ nested lists.

**Comment by prasant94** [comment]
I think I got it! I needed to use conditionals to execute code selectively. I used switch case. 

``` clojure
(defmacro with-keys [available ret-options]
  `(cond
     (nil? ~ret-options)
       ~available
     :else
       (let [uniq# (into [] (distinct ~ret-options))     ; remove duplicates
             matrices# (for [x# uniq#]
                         (case x# 
                           ~@(apply concat available)
                           nil))]       ; invalid choice (eg :P, :S)
           (into {} (filter second (zipmap uniq# matrices#))))))      ; remove where value is nil

(extend-protocol mp/PQRDecomposition
  AMatrix
    (qr [m options]
      (let
        [result (QR/decompose m)]
        (with-keys {:Q (.getQ result) :R (.getR result)} options))))
```

**Comment by mikera** [comment]
Yep, you have figured out one of the the key tricks!

You can still do a bit better though. You are constructing a bunch of intermediate objects with the `for` loop, the `filter`, the `zipmap` and the `into`. Can you figure out a way to eliminate these overheads? Ideally you want to do just one `assoc` for each key required....

Some style points:
- `cond` with a single condition can be simplified into a single `if` expression
- `(nil? xxxx)` can often be simplified to simply `xxxx` since nil if considered as a falsey value in Clojure
- I suggest passing `(:return options)` rather than the whole `options` map.
- When you use an argument multiple times in macro it is often a good idea to bind it to a gensymed local variable - something like `(let [ro# ~ret-options] .......)`. This ensures that the argument (which is a form!) only gets evaluated once. In this case it is unlikely to matter, but sometimes the argument could be a complex and expensive expression so you really want to ensure at most one evaluation.

**Comment by prasant94** [comment]
assoc returns a list of pairs, so I had to use `(into {} pairs)`

``` clojure
(defmacro with-keys [available ret-options]
  `(if ~ret-options 
     (let [uniq# (into [] (distinct ~ret-options))
           pairs# (for [x# uniq#
                           :let [m# (case x# 
                                      ~@(apply concat available)
                                      nil)]
                           :when m#]
                       (assoc nil x# m#))]
       (into {} pairs#))
     ~available))

(extend-protocol mp/PQRDecomposition
  AMatrix
    (qr [m options]
      (let
        [result (QR/decompose m)]
        (with-keys {:Q (.getQ result) :R (.getR result)} (:return options)))))
```

**Comment by mikera** [comment]
I mean `assoc` in the sense of adding a new key value mapping to a map.

Can you think of a way to build the result map, using assoc exactly once for each requested key? How would you generate code that does this for any `available` map?

**Comment by prasant94** [comment]
I would have to loop over all the requested keys and pass the result map to assoc so it adds the new key value pair to it.

**Comment by mikera** [comment]
There is a better way!

Remember that macros are different from functions.... you can do things at compile time that you couldn't do in a normal function.

**Comment by prasant94** [comment]
I used reduce. This returns nil as the value for invalid keys. This seems like a good return value as well.

``` clojure
(defmacro with-keys [available ret-options]
  `(let [ret-ops# ~ret-options]
     (if ret-ops# 
       (reduce 
           (fn [m# k#] (assoc m# k# (case k# 
                                        ~@(apply concat available)
                                        nil)))
           {}
           ret-ops#)
       ~available)))

(extend-protocol mp/PQRDecomposition
  AMatrix
    (qr [m options]
      (let
        [result (QR/decompose m)]
        (with-keys {:Q (.getQ result) :R (.getR result)} (:return options)))))
```

**Comment by prasant94** [comment]
``` clojure
=> (qr m {:return [:Q :S]})
{:S nil, :Q #<Matrix [[-0.12309149097933281,0.9045340337332908,0.40824829046386363],[-0.4923659639173309,0.30151134457776396,-0.8164965809277259],[-0.8616404368553291,-0.30151134457776396,0.4082482904638628]]>}
```

**Comment by mikera** [comment]
You don't need reduce either. You don't need _any_ looping / iteration construct in the macroexpanded code. Can you see how to do that?

I'm pushing you to think more about this one because I really want you to understand the power of macros....

**Comment by prasant94** [comment]
``` clojure
(defmacro with-keys
  [available required]
  (let [result-sym (gensym)]
    `(let
       [~result-sym {}
        ~@(mapcat (fn [[k v]] `(~result-sym (if (some #{~k} ~required) 
                                              (assoc ~result-sym ~k ~v)
                                              ~result-sym)))
                  available)]
       ~result-sym)))

(extend-protocol mp/PQRDecomposition
  AMatrix
    (qr [m options]
      (let
        [result (QR/decompose m)]
        (with-keys {:Q (.getQ result) :R (.getR result)} (:return options)))))
```

**Comment by mikera** [comment]
Looks great - I think you cracked it - well done :-)

**Pull request merged**
